jobs:
  - job: "dagster"
    pool:
      vmImage: "vs2017-win2016"
    strategy:
      matrix:
        py27-api_tests:
          TOXENV: "py27-windows-api_tests"
          python.version: "2.7"
        py36-api_tests:
          TOXENV: "py36-windows-api_tests"
          python.version: "3.6"
        py37-api_tests:
          TOXENV: "py37-windows-api_tests"
          python.version: "3.7"
        py27-cli_tests:
          TOXENV: "py27-windows-cli_tests"
          python.version: "2.7"
        py36-cli_tests:
          TOXENV: "py36-windows-cli_tests"
          python.version: "3.6"
        py37-cli_tests:
          TOXENV: "py37-windows-cli_tests"
          python.version: "3.7"
        py27-core_tests:
          TOXENV: "py27-windows-core_tests"
          python.version: "2.7"
        py36-core_tests:
          TOXENV: "py36-windows-core_tests"
          python.version: "3.6"
        py37-core_tests:
          TOXENV: "py37-windows-core_tests"
          python.version: "3.7"
        py27-general_tests:
          TOXENV: "py27-windows-general_tests"
          python.version: "2.7"
        py36-general_tests:
          TOXENV: "py36-windows-general_tests"
          python.version: "3.6"
        py37-general_tests:
          TOXENV: "py37-windows-general_tests"
          python.version: "3.7"
    variables:
      PYTHONLEGACYWINDOWSSTDIO: "1"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
          architecture: "x64"
      - script: choco install vcpython27 --yes
        condition: eq(variables['python.version'], '2.7')
        displayName: "Install vcpython27"
      - script: pip install tox
        displayName: "Install tox"
      - script: cd python_modules\dagster && tox -e %TOXENV% && cd ..\..
        displayName: "Run tests"
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: "**/test_results.xml"
          testRunTitle: "dagster $(TOXENV)"
        condition: succeededOrFailed()
